// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Age                  uint32            `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Account              int32             `protobuf:"varint,2,opt,name=account,proto3" json:"account,omitempty"`
	Name                 string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Action               string            `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Params               map[string]string `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetAccount() int32 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Person) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Test struct {
	Num1                 int32    `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2                 uint32   `protobuf:"fixed32,2,opt,name=num2,proto3" json:"num2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetNum1() int32 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *Test) GetNum2() uint32 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type Test2 struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test2) Reset()         { *m = Test2{} }
func (m *Test2) String() string { return proto.CompactTextString(m) }
func (*Test2) ProtoMessage()    {}
func (*Test2) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}

func (m *Test2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test2.Unmarshal(m, b)
}
func (m *Test2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test2.Marshal(b, m, deterministic)
}
func (m *Test2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test2.Merge(m, src)
}
func (m *Test2) XXX_Size() int {
	return xxx_messageInfo_Test2.Size(m)
}
func (m *Test2) XXX_DiscardUnknown() {
	xxx_messageInfo_Test2.DiscardUnknown(m)
}

var xxx_messageInfo_Test2 proto.InternalMessageInfo

func (m *Test2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Test3 struct {
	Num                  []int32  `protobuf:"varint,1,rep,packed,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test3) Reset()         { *m = Test3{} }
func (m *Test3) String() string { return proto.CompactTextString(m) }
func (*Test3) ProtoMessage()    {}
func (*Test3) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}

func (m *Test3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test3.Unmarshal(m, b)
}
func (m *Test3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test3.Marshal(b, m, deterministic)
}
func (m *Test3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test3.Merge(m, src)
}
func (m *Test3) XXX_Size() int {
	return xxx_messageInfo_Test3.Size(m)
}
func (m *Test3) XXX_DiscardUnknown() {
	xxx_messageInfo_Test3.DiscardUnknown(m)
}

var xxx_messageInfo_Test3 proto.InternalMessageInfo

func (m *Test3) GetNum() []int32 {
	if m != nil {
		return m.Num
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "pb.Person")
	proto.RegisterMapType((map[string]string)(nil), "pb.Person.ParamsEntry")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*Test)(nil), "pb.Test")
	proto.RegisterType((*Test2)(nil), "pb.Test2")
	proto.RegisterType((*Test3)(nil), "pb.Test3")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x49, 0xbb, 0x74, 0xed, 0x9d, 0xc2, 0x08, 0x63, 0x04, 0x45, 0x08, 0x7d, 0xca, 0x53,
	0xc0, 0xee, 0x65, 0xfa, 0x28, 0xf8, 0x3e, 0x82, 0x7f, 0x20, 0xad, 0x41, 0x44, 0x9b, 0x84, 0xa6,
	0x15, 0xf6, 0x1b, 0xfd, 0x53, 0x92, 0xdb, 0x4e, 0x7d, 0x3b, 0xe7, 0xe4, 0x5e, 0xee, 0x97, 0x03,
	0x65, 0x68, 0x55, 0x18, 0xfc, 0xe8, 0x59, 0x16, 0xda, 0xfa, 0x9b, 0x40, 0x71, 0xb2, 0x43, 0xf4,
	0x8e, 0x6d, 0x21, 0x37, 0x6f, 0x96, 0x13, 0x41, 0xe4, 0xb5, 0x4e, 0x92, 0x71, 0x58, 0x9b, 0xae,
	0xf3, 0x93, 0x1b, 0x79, 0x26, 0x88, 0xa4, 0xfa, 0x62, 0x19, 0x83, 0x95, 0x33, 0xbd, 0xe5, 0xb9,
	0x20, 0xb2, 0xd2, 0xa8, 0xd9, 0x1e, 0x0a, 0xd3, 0x8d, 0xef, 0xde, 0xf1, 0x15, 0xa6, 0x8b, 0x63,
	0x0a, 0x8a, 0x60, 0x06, 0xd3, 0x47, 0x4e, 0x45, 0x2e, 0x37, 0xcd, 0x5e, 0x85, 0x56, 0xcd, 0x37,
	0xd5, 0x09, 0x1f, 0x9e, 0xdd, 0x38, 0x9c, 0xf5, 0x32, 0x75, 0xf3, 0x00, 0x9b, 0x7f, 0x71, 0xc2,
	0xfa, 0xb0, 0x67, 0xc4, 0xaa, 0x74, 0x92, 0x6c, 0x07, 0xf4, 0xcb, 0x7c, 0x4e, 0x16, 0xa1, 0x2a,
	0x3d, 0x9b, 0xc7, 0xec, 0x48, 0xea, 0x23, 0x94, 0xda, 0xc6, 0xe0, 0x5d, 0x44, 0xf8, 0x38, 0x75,
	0x9d, 0x8d, 0x11, 0x77, 0x4b, 0x7d, 0xb1, 0x09, 0xfe, 0xd5, 0x8c, 0x86, 0x53, 0x41, 0xe4, 0x95,
	0x46, 0x5d, 0x2b, 0x58, 0xbd, 0xd8, 0x38, 0x7f, 0x6c, 0xea, 0xef, 0x71, 0x85, 0x6a, 0xd4, 0x4b,
	0xd6, 0xe0, 0xb9, 0x35, 0x66, 0x4d, 0x7d, 0x0b, 0x34, 0xcd, 0x37, 0xbf, 0x4d, 0x90, 0xbf, 0x26,
	0xea, 0xbb, 0xf9, 0xf1, 0xc0, 0x76, 0x90, 0xbb, 0xa9, 0xe7, 0x44, 0xe4, 0x92, 0x3e, 0x65, 0x5b,
	0xa2, 0x93, 0x6d, 0x0b, 0xac, 0xff, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x43, 0x46, 0x56,
	0x8a, 0x01, 0x00, 0x00,
}
