name: Redis Service Example
on: workflow_dispatch

jobs:
  # Label of the container job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        #
        ports:
          # Opens tcp port 6379 on the host and service container
          - 6379:6379
    # run steps in host
    steps:
      - run: sudo apt-get install redis-tools
      - run: redis-cli -h 127.0.0.1 -p 6379 set test-key "test key value"
      - run: redis-cli -h 127.0.0.1 -p 6379 get test-key

  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: ubuntu:20.04

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
    # run steps in ubuntu:20.04 docker container
    steps:
      - run: apt-get update; apt-get -y install redis-tools
      - run: redis-cli -h redis set test-key "test key value"
      - run: redis-cli -h redis get test-key